/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as DespreNoiIndexRouteImport } from './routes/despre-noi/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as PoliticaConfidentialitateIndexRouteImport } from './routes/politica-confidentialitate/index'
import { Route as PoliticaCookieUriIndexRouteImport } from './routes/politica-cookie-uri/index'
import { Route as PoliticaDeLivrareChar536iReturIndexRouteImport } from './routes/politica-de-livrare-și-retur/index'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as TermeniSiConditiiIndexRouteImport } from './routes/termeni-si-conditii/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CCategoryChar123SubCategoryChar125RouteImport } from './routes/c/$category.{-$subCategory}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreNoiIndexRoute = DespreNoiIndexRouteImport.update({
  id: '/despre-noi/',
  path: '/despre-noi/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaConfidentialitateIndexRoute =
  PoliticaConfidentialitateIndexRouteImport.update({
    id: '/politica-confidentialitate/',
    path: '/politica-confidentialitate/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoliticaCookieUriIndexRoute = PoliticaCookieUriIndexRouteImport.update({
  id: '/politica-cookie-uri/',
  path: '/politica-cookie-uri/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeLivrareChar536iReturIndexRoute =
  PoliticaDeLivrareChar536iReturIndexRouteImport.update({
    id: '/politica-de-livrare-și-retur/',
    path: '/politica-de-livrare-și-retur/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniSiConditiiIndexRoute = TermeniSiConditiiIndexRouteImport.update({
  id: '/termeni-si-conditii/',
  path: '/termeni-si-conditii/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryChar123SubCategoryChar125Route =
  CCategoryChar123SubCategoryChar125RouteImport.update({
    id: '/c/$category/{-$subCategory}',
    path: '/c/$category/{-$subCategory}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/upload': typeof ApiUploadRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/despre-noi/': typeof DespreNoiIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/politica-confidentialitate/': typeof PoliticaConfidentialitateIndexRoute
  '/politica-cookie-uri/': typeof PoliticaCookieUriIndexRoute
  '/politica-de-livrare-și-retur/': typeof PoliticaDeLivrareChar536iReturIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/termeni-si-conditii/': typeof TermeniSiConditiiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$category/{-$subCategory}': typeof CCategoryChar123SubCategoryChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/upload': typeof ApiUploadRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout': typeof CheckoutIndexRoute
  '/contact': typeof ContactIndexRoute
  '/despre-noi': typeof DespreNoiIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateIndexRoute
  '/politica-cookie-uri': typeof PoliticaCookieUriIndexRoute
  '/politica-de-livrare-și-retur': typeof PoliticaDeLivrareChar536iReturIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$category/{-$subCategory}': typeof CCategoryChar123SubCategoryChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/upload': typeof ApiUploadRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/despre-noi/': typeof DespreNoiIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/politica-confidentialitate/': typeof PoliticaConfidentialitateIndexRoute
  '/politica-cookie-uri/': typeof PoliticaCookieUriIndexRoute
  '/politica-de-livrare-și-retur/': typeof PoliticaDeLivrareChar536iReturIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/termeni-si-conditii/': typeof TermeniSiConditiiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$category/{-$subCategory}': typeof CCategoryChar123SubCategoryChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/upload'
    | '/orders/$id'
    | '/product/$slug'
    | '/checkout/'
    | '/contact/'
    | '/despre-noi/'
    | '/orders/'
    | '/politica-confidentialitate/'
    | '/politica-cookie-uri/'
    | '/politica-de-livrare-și-retur/'
    | '/sign-in/'
    | '/termeni-si-conditii/'
    | '/api/auth/$'
    | '/c/$category/{-$subCategory}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/upload'
    | '/orders/$id'
    | '/product/$slug'
    | '/checkout'
    | '/contact'
    | '/despre-noi'
    | '/orders'
    | '/politica-confidentialitate'
    | '/politica-cookie-uri'
    | '/politica-de-livrare-și-retur'
    | '/sign-in'
    | '/termeni-si-conditii'
    | '/api/auth/$'
    | '/c/$category/{-$subCategory}'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/upload'
    | '/orders/$id'
    | '/product/$slug'
    | '/checkout/'
    | '/contact/'
    | '/despre-noi/'
    | '/orders/'
    | '/politica-confidentialitate/'
    | '/politica-cookie-uri/'
    | '/politica-de-livrare-și-retur/'
    | '/sign-in/'
    | '/termeni-si-conditii/'
    | '/api/auth/$'
    | '/c/$category/{-$subCategory}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiUploadRoute: typeof ApiUploadRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  DespreNoiIndexRoute: typeof DespreNoiIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PoliticaConfidentialitateIndexRoute: typeof PoliticaConfidentialitateIndexRoute
  PoliticaCookieUriIndexRoute: typeof PoliticaCookieUriIndexRoute
  PoliticaDeLivrareChar536iReturIndexRoute: typeof PoliticaDeLivrareChar536iReturIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  TermeniSiConditiiIndexRoute: typeof TermeniSiConditiiIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CCategoryChar123SubCategoryChar125Route: typeof CCategoryChar123SubCategoryChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi/': {
      id: '/despre-noi/'
      path: '/despre-noi'
      fullPath: '/despre-noi/'
      preLoaderRoute: typeof DespreNoiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-confidentialitate/': {
      id: '/politica-confidentialitate/'
      path: '/politica-confidentialitate'
      fullPath: '/politica-confidentialitate/'
      preLoaderRoute: typeof PoliticaConfidentialitateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookie-uri/': {
      id: '/politica-cookie-uri/'
      path: '/politica-cookie-uri'
      fullPath: '/politica-cookie-uri/'
      preLoaderRoute: typeof PoliticaCookieUriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-livrare-și-retur/': {
      id: '/politica-de-livrare-și-retur/'
      path: '/politica-de-livrare-și-retur'
      fullPath: '/politica-de-livrare-și-retur/'
      preLoaderRoute: typeof PoliticaDeLivrareChar536iReturIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni-si-conditii/': {
      id: '/termeni-si-conditii/'
      path: '/termeni-si-conditii'
      fullPath: '/termeni-si-conditii/'
      preLoaderRoute: typeof TermeniSiConditiiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category/{-$subCategory}': {
      id: '/c/$category/{-$subCategory}'
      path: '/c/$category/{-$subCategory}'
      fullPath: '/c/$category/{-$subCategory}'
      preLoaderRoute: typeof CCategoryChar123SubCategoryChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiUploadRoute: ApiUploadRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  DespreNoiIndexRoute: DespreNoiIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PoliticaConfidentialitateIndexRoute: PoliticaConfidentialitateIndexRoute,
  PoliticaCookieUriIndexRoute: PoliticaCookieUriIndexRoute,
  PoliticaDeLivrareChar536iReturIndexRoute:
    PoliticaDeLivrareChar536iReturIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  TermeniSiConditiiIndexRoute: TermeniSiConditiiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CCategoryChar123SubCategoryChar125Route:
    CCategoryChar123SubCategoryChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
