/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as OrderIdRouteImport } from './routes/order/$id'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as CCategoryChar123SubCategoryChar125RouteImport } from './routes/c/$category.{-$subCategory}'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryChar123SubCategoryChar125Route =
  CCategoryChar123SubCategoryChar125RouteImport.update({
    id: '/c/$category/{-$subCategory}',
    path: '/c/$category/{-$subCategory}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/order/': typeof OrderIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$category/{-$subCategory}': typeof CCategoryChar123SubCategoryChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout': typeof CheckoutIndexRoute
  '/order': typeof OrderIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$category/{-$subCategory}': typeof CCategoryChar123SubCategoryChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/order/': typeof OrderIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$category/{-$subCategory}': typeof CCategoryChar123SubCategoryChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/upload'
    | '/order/$id'
    | '/product/$slug'
    | '/checkout/'
    | '/order/'
    | '/sign-in/'
    | '/api/auth/$'
    | '/c/$category/{-$subCategory}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/upload'
    | '/order/$id'
    | '/product/$slug'
    | '/checkout'
    | '/order'
    | '/sign-in'
    | '/api/auth/$'
    | '/c/$category/{-$subCategory}'
  id:
    | '__root__'
    | '/'
    | '/api/upload'
    | '/order/$id'
    | '/product/$slug'
    | '/checkout/'
    | '/order/'
    | '/sign-in/'
    | '/api/auth/$'
    | '/c/$category/{-$subCategory}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiUploadRoute: typeof ApiUploadRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CCategoryChar123SubCategoryChar125Route: typeof CCategoryChar123SubCategoryChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category/{-$subCategory}': {
      id: '/c/$category/{-$subCategory}'
      path: '/c/$category/{-$subCategory}'
      fullPath: '/c/$category/{-$subCategory}'
      preLoaderRoute: typeof CCategoryChar123SubCategoryChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiUploadRoute: ApiUploadRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CCategoryChar123SubCategoryChar125Route:
    CCategoryChar123SubCategoryChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
